// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wxhinjdceqneufvanfqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4aGluamRjZXFuZXVmdmFuZnFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5NzYzOTgsImV4cCI6MjA3MDU1MjM5OH0.203JRy5TpGVf8bJfpgJQjBUiHvT8QVczB0U_s3bHOP0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);